name:                 halatro
version:              0.1.0.0
visibility:           public
id:                   halatro-0.1.0.0-KCnpH0I3HHpAKBhV6tB7aN
key:                  halatro-0.1.0.0-KCnpH0I3HHpAKBhV6tB7aN
license:              BSD-3-Clause
copyright:            2025 Alex Dixon
maintainer:           alexander.dixon@warwick.ac.uk
author:               Alex Dixon
description:
    A simple implementation of the basic Balatro ruleset in Haskell, including a terminal user interface.

abi:                  e316698157121952365112f8d1bc0ded
exposed:              True
exposed-modules:
    CourseworkOne Halatro.BasicGame Halatro.Constants Halatro.Types

hidden-modules:       Paths_halatro
import-dirs:
    /dcs/24/u5594153/year1/cs141/cs141-halatro/.stack-work/install/x86_64-linux/ec8a2f8bbd124ba0bf429c4f9e63e032f3fd0a1ad18b7002e1c8b57981691fa9/9.4.8/lib/x86_64-linux-ghc-9.4.8/halatro-0.1.0.0-KCnpH0I3HHpAKBhV6tB7aN

library-dirs:
    /dcs/24/u5594153/year1/cs141/cs141-halatro/.stack-work/install/x86_64-linux/ec8a2f8bbd124ba0bf429c4f9e63e032f3fd0a1ad18b7002e1c8b57981691fa9/9.4.8/lib/x86_64-linux-ghc-9.4.8/halatro-0.1.0.0-KCnpH0I3HHpAKBhV6tB7aN
    /modules/cs141/.stack-libs

library-dirs-static:
    /dcs/24/u5594153/year1/cs141/cs141-halatro/.stack-work/install/x86_64-linux/ec8a2f8bbd124ba0bf429c4f9e63e032f3fd0a1ad18b7002e1c8b57981691fa9/9.4.8/lib/x86_64-linux-ghc-9.4.8/halatro-0.1.0.0-KCnpH0I3HHpAKBhV6tB7aN
    /modules/cs141/.stack-libs

dynamic-library-dirs:
    /dcs/24/u5594153/year1/cs141/cs141-halatro/.stack-work/install/x86_64-linux/ec8a2f8bbd124ba0bf429c4f9e63e032f3fd0a1ad18b7002e1c8b57981691fa9/9.4.8/lib/x86_64-linux-ghc-9.4.8
    /modules/cs141/.stack-libs

data-dir:
    /dcs/24/u5594153/year1/cs141/cs141-halatro/.stack-work/install/x86_64-linux/ec8a2f8bbd124ba0bf429c4f9e63e032f3fd0a1ad18b7002e1c8b57981691fa9/9.4.8/share/x86_64-linux-ghc-9.4.8/halatro-0.1.0.0

hs-libraries:         HShalatro-0.1.0.0-KCnpH0I3HHpAKBhV6tB7aN
depends:
    base-4.17.2.1 containers-0.6.7
    random-1.2.1.3-DvyRP4kkfYs6BLBMkeSNj6 text-2.0.2 time-1.12.2

haddock-interfaces:
    /dcs/24/u5594153/year1/cs141/cs141-halatro/.stack-work/install/x86_64-linux/ec8a2f8bbd124ba0bf429c4f9e63e032f3fd0a1ad18b7002e1c8b57981691fa9/9.4.8/doc/halatro-0.1.0.0/halatro.haddock

haddock-html:
    /dcs/24/u5594153/year1/cs141/cs141-halatro/.stack-work/install/x86_64-linux/ec8a2f8bbd124ba0bf429c4f9e63e032f3fd0a1ad18b7002e1c8b57981691fa9/9.4.8/doc/halatro-0.1.0.0
